
import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import fetch from 'isomorphic-unfetch';
import { useState} from 'react';

const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   const handleButtonClick = async (e) => {
//     e.preventDefault()
//     console.log("Button Clicked")
//     const respone = await fetch(`/api/checkport?port=80`);
//     const data = await response.json();
//     console.log(data);
//   }
export default function Home() {
  const [url, setUrl] = useState('');


  const handleButtonClick = async () => {
    const response = await fetch('http://localhost:5000/get_url');
    const data = await response.json();
    console.log(data.url);
    // alert(data.url);
    setUrl(data.url);
  };

  return (
    <>
    
      <Head>
        <title>Maouque-CTF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={`${styles.main} ${inter.className}`}>
          <div className={styles.description}>
              <h1>Maouque-CTF&nbsp;</h1>
          </div>
          
          <div>
            <h3>Description:</h3>
            <p>It is an easy way in. Someone didn't secure their system. 
              I see there are some on going operation. I believe this person is performing some sort of red team automation.
              What can we do with these agents. I notice one of them looks odd. Can you investigate this?&nbsp;</p>
          </div>

          <div>
               <p>Note: Please don't use automation tools or bruteforce as it is not needed for this challenge. 
                All you need is research skill&nbsp;
               </p>
          </div>   

          <div>
            <button onClick={handleButtonClick}>Start</button>
          </div>
          <code className={styles.code}>{url && <p>Link to challenge: {url} </p>}</code>
          

        </main>
      
    
    </>
  )
}
